# Generated by Django 5.0.4 on 2024-12-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usermodel_email_usermodel_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
    ]
