# Generated by Django 5.0.4 on 2024-12-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_usermodel_email_remove_usermodel_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
        migrations.AddField(
            model_name='documentsmodel',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.usermodel'),
            preserve_default=False,
        ),
    ]
